//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Net
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Факторы.
    /// </summary>
    // *** Start programmer edit section *** (Факторы CustomAttributes)

    // *** End programmer edit section *** (Факторы CustomAttributes)
    public enum Факторы
    {
        
        // *** Start programmer edit section *** (Факторы.ВзаимСРуков CustomAttributes)

        // *** End programmer edit section *** (Факторы.ВзаимСРуков CustomAttributes)
        [Caption("Взаимоотношення с руководителем")]
        ВзаимСРуков,
        
        // *** Start programmer edit section *** (Факторы.ВзаимCКоллег CustomAttributes)

        // *** End programmer edit section *** (Факторы.ВзаимCКоллег CustomAttributes)
        [Caption("Взаимоотношения с коллегами")]
        ВзаимCКоллег,
        
        // *** Start programmer edit section *** (Факторы.СанитГигиеУсл CustomAttributes)

        // *** End programmer edit section *** (Факторы.СанитГигиеУсл CustomAttributes)
        [Caption("Санитарно-гигиенические условия")]
        СанитГигиеУсл,
        
        // *** Start programmer edit section *** (Факторы.СнабНеобхИнст CustomAttributes)

        // *** End programmer edit section *** (Факторы.СнабНеобхИнст CustomAttributes)
        [Caption("Снабжение необходимыми инструментами")]
        СнабНеобхИнст,
    }
}
